apiVersion: v1
kind: Secret
metadata:
  name: encurtai-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "encurtai123"
  JWT_SECRET_KEY: "sua-chave-jwt-super-secreta-minimo-32-caracteres"
  FRONTEND_URL: "http://seu-dominio.com"
